name: Build and push to polla.dev

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'

      - name: Build site
        run: hugo --minify

      - name: Push public to polla.dev repo
        env:
          POLLAPAT: ${{ secrets.POLLAPAT }}
        run: |
          set -e
          TARGET_REPO="https://x-access-token:${POLLAPAT}@github.com/polla-fattah/polla.dev.git"
          TARGET_DIR="vuejs"

          git clone --depth 1 "$TARGET_REPO" target || (git clone "$TARGET_REPO" target)
          rm -rf target/${TARGET_DIR}
          mkdir -p target/${TARGET_DIR}
          cp -r public/* target/${TARGET_DIR}/
          cd target
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "chore: update vuejs site from vuejs repo" || echo "No changes to commit"
          git push origin HEAD:main
